// GENERATED FILE — do not edit by hand.
// Source: client/src/data/blog-posts.ts
// Regenerate: npm run gen:blog

export const BLOG_ROUTE_META = {
  "/blog/ai-detector-plagiarism-assignment-bangladesh": { title: "AI Detectors and University Assignments in Bangladesh: What Actually Gets You Caught | AI Team Premium", description: "Universities in Bangladesh are increasingly running AI detection on submissions. Here's how these tools actually work, why they produce false positives, and...", canonical: "https://www.aiteampremium.com/blog/ai-detector-plagiarism-assignment-bangladesh", lang: "en" },
  "/blog/ai-diye-cv-cover-letter-chakri-bangla": { title: "AI দিয়ে CV ও কভার লেটার বানানো: চাকরিপ্রার্থীদের জন্য বাংলা গাইড | AI Team Premium", description: "ATS সিস্টেমে আটকে যাওয়া CV থেকে শুরু করে ইন্টারভিউ প্রস্তুতি — AI দিয়ে চাকরির আবেদন কিভাবে শক্তিশালী করবেন, বাস্তব উদাহরণসহ।", canonical: "https://www.aiteampremium.com/blog/ai-diye-cv-cover-letter-chakri-bangla", lang: "bn" },
  "/blog/ai-diye-english-shekha-bangla-guide": { title: "AI দিয়ে ইংরেজি শেখা: প্রতিদিন ৩০ মিনিটের বাস্তব পরিকল্পনা | AI Team Premium", description: "কথা বলার জড়তা, গ্রামার ভুল, IELTS প্রস্তুতি — AI-কে ব্যক্তিগত ইংরেজি টিউটর হিসেবে ব্যবহার করার সম্পূর্ণ বাংলা গাইড, বাস্তব prompt সহ।", canonical: "https://www.aiteampremium.com/blog/ai-diye-english-shekha-bangla-guide", lang: "bn" },
  "/blog/ai-diye-income-bangladesh-bangla-guide": { title: "AI দিয়ে ঘরে বসে ইনকাম: বাংলাদেশে বাস্তব ৭টি উপায় (২০২৬) | AI Team Premium", description: "AI দিয়ে টাকা আয় করার নামে অনেক ভুয়া প্রতিশ্রুতি ঘুরছে। এখানে শুধু বাস্তব উপায়গুলো — যেগুলোতে বাংলাদেশ থেকে সত্যিই আয় করা সম্ভব, কত সময় লাগে, আর কোন AI...", canonical: "https://www.aiteampremium.com/blog/ai-diye-income-bangladesh-bangla-guide", lang: "bn" },
  "/blog/ai-freelancer-career-roadmap-which-tools-first-bangladesh": { title: "AI Freelancer Career Roadmap: Which Tools to Learn First in Bangladesh | AI Team Premium", description: "Buying every AI subscription at once wastes money and teaches you nothing well. Here's the order that actually works — what to learn in month 1, what to add...", canonical: "https://www.aiteampremium.com/blog/ai-freelancer-career-roadmap-which-tools-first-bangladesh", lang: "en" },
  "/blog/ai-skills-for-job-seekers-bangladesh-30-day-roadmap": { title: "AI Skills for Job Seekers in Bangladesh: A 30-Day Roadmap | AI Team Premium", description: "A CV rewrite alone doesn't get you hired. Here's a 30-day plan that uses AI for the CV, the applications, the interview prep and the follow-up — the full...", canonical: "https://www.aiteampremium.com/blog/ai-skills-for-job-seekers-bangladesh-30-day-roadmap", lang: "en" },
  "/blog/ai-tools-fiverr-upwork-freelancers-bangladesh": { title: "AI Tools for Fiverr & Upwork Freelancers in Bangladesh: The Complete Toolkit | AI Team Premium", description: "Bangladesh is one of the largest freelancer markets in the world. Here's the AI toolkit that actually moves the needle on proposal win-rate, delivery speed,...", canonical: "https://www.aiteampremium.com/blog/ai-tools-fiverr-upwork-freelancers-bangladesh", lang: "en" },
  "/blog/best-ai-tools-bangladeshi-university-students": { title: "5 Best AI Tools for Bangladeshi University Students in 2026 | AI Team Premium", description: "From assignment research to IELTS prep and thesis writing — a practical, budget-first breakdown of which AI subscriptions are actually worth ৳499/month for...", canonical: "https://www.aiteampremium.com/blog/best-ai-tools-bangladeshi-university-students", lang: "en" },
  "/blog/bkash-diye-chatgpt-kena-bangla-guide": { title: "বিকাশ দিয়ে ChatGPT কেনার সম্পূর্ণ গাইড (২০২৬) | AI Team Premium", description: "ইন্টারন্যাশনাল কার্ড ছাড়া বিকাশ বা নগদ দিয়ে ChatGPT Plus কিভাবে নেবেন — ধাপে ধাপে, প্রতারণা এড়ানোর উপায়সহ সম্পূর্ণ বাংলা গাইড।", canonical: "https://www.aiteampremium.com/blog/bkash-diye-chatgpt-kena-bangla-guide", lang: "bn" },
  "/blog/canva-pro-price-bangladesh-worth-it": { title: "Canva Pro Price in Bangladesh (2026): Is It Worth Paying For? | AI Team Premium", description: "Canva's free tier is genuinely good — so when does Pro actually pay for itself? An honest breakdown for Bangladeshi students, freelancers and small business...", canonical: "https://www.aiteampremium.com/blog/canva-pro-price-bangladesh-worth-it", lang: "en" },
  "/blog/chatgpt-kivabe-babohar-korben-bangla": { title: "ChatGPT কিভাবে ব্যবহার করবেন: শুরু থেকে শেষ পর্যন্ত বাংলা গাইড | AI Team Premium", description: "ChatGPT অ্যাকাউন্ট খোলা থেকে ভালো prompt লেখা পর্যন্ত — বাংলাদেশি ব্যবহারকারীদের জন্য সম্পূর্ণ বাংলা গাইড। কোন ভুলগুলো নতুনরা করে আর কীভাবে এড়াবেন।", canonical: "https://www.aiteampremium.com/blog/chatgpt-kivabe-babohar-korben-bangla", lang: "bn" },
  "/blog/chatgpt-plus-price-bangladesh-bkash-guide": { title: "ChatGPT Plus Price in Bangladesh (2026): Full bKash & Nagad Payment Guide | AI Team Premium", description: "OpenAI doesn't accept Bangladeshi cards directly. Here's exactly what ChatGPT Plus costs in BDT, how shared vs personal seats work, and how to pay with...", canonical: "https://www.aiteampremium.com/blog/chatgpt-plus-price-bangladesh-bkash-guide", lang: "en" },
  "/blog/chatgpt-vs-claude-vs-gemini-bangladesh-freelancers": { title: "ChatGPT vs Claude vs Gemini: Which AI Should Freelancers in Bangladesh Actually Use? | AI Team Premium", description: "A practical comparison for Bangladeshi Fiverr and Upwork freelancers — not a spec sheet, but which tool wins for proposals, code, long documents, and client...", canonical: "https://www.aiteampremium.com/blog/chatgpt-vs-claude-vs-gemini-bangladesh-freelancers", lang: "en" },
  "/blog/developer-ai-roadmap-github-copilot-vs-cursor-bangladesh": { title: "Developer's AI Roadmap: GitHub Copilot vs Cursor — Which to Learn First | AI Team Premium", description: "Both are AI coding assistants, both cost roughly the same at entry, and they solve different problems. Here's how to decide which one to start with, and...", canonical: "https://www.aiteampremium.com/blog/developer-ai-roadmap-github-copilot-vs-cursor-bangladesh", lang: "en" },
  "/blog/live-ai-training-bangladesh-what-you-get": { title: "Free & Paid Live AI Training in Bangladesh: What You Actually Get From a Support Session | AI Team Premium", description: "Subscriptions solve access — not know-how. Here's what AI Team Premium's live, Bangla-language AI coaching sessions actually cover, and who they're built...", canonical: "https://www.aiteampremium.com/blog/live-ai-training-bangladesh-what-you-get", lang: "en" },
  "/blog/pay-chatgpt-without-international-credit-card-bangladesh": { title: "How to Pay for ChatGPT Plus Without an International Credit Card in Bangladesh | AI Team Premium", description: "No dual-currency card? No problem. Here are the real options Bangladeshi users have for accessing premium AI subscriptions — and the tradeoffs of each.", canonical: "https://www.aiteampremium.com/blog/pay-chatgpt-without-international-credit-card-bangladesh", lang: "en" },
  "/blog/shared-vs-personal-ai-subscription-which-to-buy": { title: "Shared vs Personal AI Subscriptions: Which Should You Actually Buy? | AI Team Premium", description: "Shared seats cost a fraction of personal accounts — but they come with real rules and real tradeoffs. A straight comparison so you buy the right one the...", canonical: "https://www.aiteampremium.com/blog/shared-vs-personal-ai-subscription-which-to-buy", lang: "en" },
  "/blog/video-editor-ai-roadmap-capcut-runway-elevenlabs-bangladesh": { title: "Video Editor's AI Roadmap: CapCut, Runway and ElevenLabs for Bangladeshi Creators | AI Team Premium", description: "Three tools cover almost every short-form and client video workflow — but they solve different problems and cost very different amounts. Here's what to...", canonical: "https://www.aiteampremium.com/blog/video-editor-ai-roadmap-capcut-runway-elevenlabs-bangladesh", lang: "en" },
};

export const BLOG_PATHS = Object.keys(BLOG_ROUTE_META);

// Article fields for BlogPosting schema. Separate from BLOG_ROUTE_META because
// that is <head> metadata; this is what the post *is*. publishedDate is null
// where the post does not state one — an absent date is emitted as no date
// rather than as today's, which would be a claim we cannot support.
export const BLOG_ARTICLES = {
  "/blog/ai-detector-plagiarism-assignment-bangladesh": { headline: "AI Detectors and University Assignments in Bangladesh: What Actually Gets You Caught", description: "Universities in Bangladesh are increasingly running AI detection on submissions. Here's how these tools actually work, why they produce false positives, and...", datePublished: "2026-07-26", lang: "en" },
  "/blog/ai-diye-cv-cover-letter-chakri-bangla": { headline: "AI দিয়ে CV ও কভার লেটার বানানো: চাকরিপ্রার্থীদের জন্য বাংলা গাইড", description: "ATS সিস্টেমে আটকে যাওয়া CV থেকে শুরু করে ইন্টারভিউ প্রস্তুতি — AI দিয়ে চাকরির আবেদন কিভাবে শক্তিশালী করবেন, বাস্তব উদাহরণসহ।", datePublished: "2026-07-30", lang: "bn" },
  "/blog/ai-diye-english-shekha-bangla-guide": { headline: "AI দিয়ে ইংরেজি শেখা: প্রতিদিন ৩০ মিনিটের বাস্তব পরিকল্পনা", description: "কথা বলার জড়তা, গ্রামার ভুল, IELTS প্রস্তুতি — AI-কে ব্যক্তিগত ইংরেজি টিউটর হিসেবে ব্যবহার করার সম্পূর্ণ বাংলা গাইড, বাস্তব prompt সহ।", datePublished: "2026-07-30", lang: "bn" },
  "/blog/ai-diye-income-bangladesh-bangla-guide": { headline: "AI দিয়ে ঘরে বসে ইনকাম: বাংলাদেশে বাস্তব ৭টি উপায় (২০২৬)", description: "AI দিয়ে টাকা আয় করার নামে অনেক ভুয়া প্রতিশ্রুতি ঘুরছে। এখানে শুধু বাস্তব উপায়গুলো — যেগুলোতে বাংলাদেশ থেকে সত্যিই আয় করা সম্ভব, কত সময় লাগে, আর কোন AI...", datePublished: "2026-07-14", lang: "bn" },
  "/blog/ai-freelancer-career-roadmap-which-tools-first-bangladesh": { headline: "AI Freelancer Career Roadmap: Which Tools to Learn First in Bangladesh", description: "Buying every AI subscription at once wastes money and teaches you nothing well. Here's the order that actually works — what to learn in month 1, what to add...", datePublished: "2026-07-31", lang: "en" },
  "/blog/ai-skills-for-job-seekers-bangladesh-30-day-roadmap": { headline: "AI Skills for Job Seekers in Bangladesh: A 30-Day Roadmap", description: "A CV rewrite alone doesn't get you hired. Here's a 30-day plan that uses AI for the CV, the applications, the interview prep and the follow-up — the full...", datePublished: "2026-07-31", lang: "en" },
  "/blog/ai-tools-fiverr-upwork-freelancers-bangladesh": { headline: "AI Tools for Fiverr & Upwork Freelancers in Bangladesh: The Complete Toolkit", description: "Bangladesh is one of the largest freelancer markets in the world. Here's the AI toolkit that actually moves the needle on proposal win-rate, delivery speed,...", datePublished: "2026-07-02", lang: "en" },
  "/blog/best-ai-tools-bangladeshi-university-students": { headline: "5 Best AI Tools for Bangladeshi University Students in 2026", description: "From assignment research to IELTS prep and thesis writing — a practical, budget-first breakdown of which AI subscriptions are actually worth ৳499/month for...", datePublished: "2026-06-10", lang: "en" },
  "/blog/bkash-diye-chatgpt-kena-bangla-guide": { headline: "বিকাশ দিয়ে ChatGPT কেনার সম্পূর্ণ গাইড (২০২৬)", description: "ইন্টারন্যাশনাল কার্ড ছাড়া বিকাশ বা নগদ দিয়ে ChatGPT Plus কিভাবে নেবেন — ধাপে ধাপে, প্রতারণা এড়ানোর উপায়সহ সম্পূর্ণ বাংলা গাইড।", datePublished: "2026-07-30", lang: "bn" },
  "/blog/canva-pro-price-bangladesh-worth-it": { headline: "Canva Pro Price in Bangladesh (2026): Is It Worth Paying For?", description: "Canva's free tier is genuinely good — so when does Pro actually pay for itself? An honest breakdown for Bangladeshi students, freelancers and small business...", datePublished: "2026-07-22", lang: "en" },
  "/blog/chatgpt-kivabe-babohar-korben-bangla": { headline: "ChatGPT কিভাবে ব্যবহার করবেন: শুরু থেকে শেষ পর্যন্ত বাংলা গাইড", description: "ChatGPT অ্যাকাউন্ট খোলা থেকে ভালো prompt লেখা পর্যন্ত — বাংলাদেশি ব্যবহারকারীদের জন্য সম্পূর্ণ বাংলা গাইড। কোন ভুলগুলো নতুনরা করে আর কীভাবে এড়াবেন।", datePublished: "2026-07-18", lang: "bn" },
  "/blog/chatgpt-plus-price-bangladesh-bkash-guide": { headline: "ChatGPT Plus Price in Bangladesh (2026): Full bKash & Nagad Payment Guide", description: "OpenAI doesn't accept Bangladeshi cards directly. Here's exactly what ChatGPT Plus costs in BDT, how shared vs personal seats work, and how to pay with...", datePublished: "2026-06-02", lang: "en" },
  "/blog/chatgpt-vs-claude-vs-gemini-bangladesh-freelancers": { headline: "ChatGPT vs Claude vs Gemini: Which AI Should Freelancers in Bangladesh Actually Use?", description: "A practical comparison for Bangladeshi Fiverr and Upwork freelancers — not a spec sheet, but which tool wins for proposals, code, long documents, and client...", datePublished: "2026-06-18", lang: "en" },
  "/blog/developer-ai-roadmap-github-copilot-vs-cursor-bangladesh": { headline: "Developer's AI Roadmap: GitHub Copilot vs Cursor — Which to Learn First", description: "Both are AI coding assistants, both cost roughly the same at entry, and they solve different problems. Here's how to decide which one to start with, and...", datePublished: "2026-07-31", lang: "en" },
  "/blog/live-ai-training-bangladesh-what-you-get": { headline: "Free & Paid Live AI Training in Bangladesh: What You Actually Get From a Support Session", description: "Subscriptions solve access — not know-how. Here's what AI Team Premium's live, Bangla-language AI coaching sessions actually cover, and who they're built...", datePublished: "2026-07-10", lang: "en" },
  "/blog/pay-chatgpt-without-international-credit-card-bangladesh": { headline: "How to Pay for ChatGPT Plus Without an International Credit Card in Bangladesh", description: "No dual-currency card? No problem. Here are the real options Bangladeshi users have for accessing premium AI subscriptions — and the tradeoffs of each.", datePublished: "2026-06-25", lang: "en" },
  "/blog/shared-vs-personal-ai-subscription-which-to-buy": { headline: "Shared vs Personal AI Subscriptions: Which Should You Actually Buy?", description: "Shared seats cost a fraction of personal accounts — but they come with real rules and real tradeoffs. A straight comparison so you buy the right one the...", datePublished: "2026-07-29", lang: "en" },
  "/blog/video-editor-ai-roadmap-capcut-runway-elevenlabs-bangladesh": { headline: "Video Editor's AI Roadmap: CapCut, Runway and ElevenLabs for Bangladeshi Creators", description: "Three tools cover almost every short-form and client video workflow — but they solve different problems and cost very different amounts. Here's what to...", datePublished: "2026-07-31", lang: "en" },
};
