// GENERATED FILE — do not edit by hand.
// Source: client/src/data/products-catalog.json + shared/category-intros.js
// Regenerate: npm run gen:category

export const CATEGORY_ROUTE_META = {
  "/category/ai-assistant": { title: "AI Assistants in Bangladesh — 11 Tools from ৳1,196/mo | AI Team Premium", description: "AI chat assistants in Bangladesh — ChatGPT, Claude, Gemini, Perplexity and more. Pay with bKash or Nagad, no international card needed.", canonical: "https://www.aiteampremium.com/category/ai-assistant" },
  "/category/ai-code": { title: "Coding Tools in Bangladesh — 7 Tools from ৳590/mo | AI Team Premium", description: "AI coding tools in Bangladesh — GitHub Copilot, Cursor, Windsurf, Replit and more for developers. Pay via bKash or Nagad, no international card.", canonical: "https://www.aiteampremium.com/category/ai-code" },
  "/category/ai-design": { title: "Design Tools in Bangladesh — 4 Tools from ৳1,728/mo | AI Team Premium", description: "AI design tools in Bangladesh — Canva, Figma, Adobe Creative Cloud and more for graphics, UI and brand work. Pay with bKash or Nagad.", canonical: "https://www.aiteampremium.com/category/ai-design" },
  "/category/ai-image": { title: "Image Generation Tools in Bangladesh — 8 Tools from ৳450/mo | AI Team Premium", description: "AI image tools in Bangladesh — Midjourney, Ideogram, Recraft, Photoroom and more for generation, editing and product photos. bKash accepted.", canonical: "https://www.aiteampremium.com/category/ai-image" },
  "/category/ai-learning": { title: "Learning Tools in Bangladesh — 1 Tool from ৳2,304/mo | AI Team Premium", description: "Online learning subscriptions in Bangladesh — Coursera and course platforms with certificates. Pay in BDT via bKash or Nagad.", canonical: "https://www.aiteampremium.com/category/ai-learning" },
  "/category/ai-video": { title: "Video Generation Tools in Bangladesh — 13 Tools from ৳270/mo | AI Team Premium", description: "AI video tools in Bangladesh — CapCut, Runway, Kling, Luma and more for editing, captions and AI video generation. bKash and Nagad accepted.", canonical: "https://www.aiteampremium.com/category/ai-video" },
  "/category/ai-voice-music": { title: "Voice & Music Tools in Bangladesh — 7 Tools from ৳499/mo | AI Team Premium", description: "AI voice and music tools in Bangladesh — ElevenLabs, Murf, Suno and more for voiceover, narration and music generation. Pay with bKash or Nagad.", canonical: "https://www.aiteampremium.com/category/ai-voice-music" },
  "/category/ai-workspace": { title: "Workspace Tools in Bangladesh — 14 Tools from ৳800/mo | AI Team Premium", description: "AI workspace and productivity tools in Bangladesh — Notion, Miro, Airtable, ClickUp, meeting assistants and more. Pay via bKash or Nagad.", canonical: "https://www.aiteampremium.com/category/ai-workspace" },
  "/category/ai-writing": { title: "Writing Tools in Bangladesh — 4 Tools from ৳390/mo | AI Team Premium", description: "AI writing tools in Bangladesh — Grammarly, QuillBot, Jasper and more for grammar, paraphrasing and content. bKash and Nagad accepted.", canonical: "https://www.aiteampremium.com/category/ai-writing" },
  "/category/automation": { title: "Automation Tools in Bangladesh — 2 Tools from ৳1,552/mo | AI Team Premium", description: "Automation tools in Bangladesh — Zapier, Make and workflow automation to connect your apps without code. Pay via bKash or Nagad.", canonical: "https://www.aiteampremium.com/category/automation" },
  "/category/bundles": { title: "AI Tool Bundles in Bangladesh — 4 Tools from ৳449 | AI Team Premium", description: "AI tool bundles in Bangladesh — curated multi-tool packages at a lower combined price. Pay via bKash, Nagad or bank transfer.", canonical: "https://www.aiteampremium.com/category/bundles" },
  "/category/seo": { title: "SEO & Marketing Tools in Bangladesh — 3 Tools from ৳4,992/mo | AI Team Premium", description: "SEO and marketing tools in Bangladesh — Semrush, Ahrefs, Surfer SEO and more for keyword research and rank tracking. bKash accepted.", canonical: "https://www.aiteampremium.com/category/seo" },
};

export const CATEGORY_PATHS = Object.keys(CATEGORY_ROUTE_META);
