// GENERATED FILE — do not edit by hand.
// Source: client/src/lib/tool-compare.ts (POPULAR_PAIRS + NAMES) and the
// TOOL_META export of each client/src/pages/tools/*.tsx
// Regenerate: npm run gen:compare

export const COMPARE_ROUTE_META = {
  "/compare/canva-vs-midjourney": { title: "Canva Pro vs Midjourney in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Canva Pro (from ৳2,190/mo) and Midjourney (from ৳4,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/canva-vs-midjourney" },
  "/compare/chatgpt-vs-claude": { title: "ChatGPT Plus vs Claude Pro in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of ChatGPT Plus (from ৳2,990/mo) and Claude Pro (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/claude-vs-chatgpt" },
  "/compare/chatgpt-vs-copilot": { title: "ChatGPT Plus vs GitHub Copilot Pro in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of ChatGPT Plus (from ৳2,990/mo) and GitHub Copilot Pro (from ৳1,495/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/copilot-vs-chatgpt" },
  "/compare/chatgpt-vs-gemini": { title: "ChatGPT Plus vs Gemini Advanced in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of ChatGPT Plus (from ৳2,990/mo) and Gemini Advanced (from ৳3,390/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/gemini-vs-chatgpt" },
  "/compare/chatgpt-vs-google-ai-pro": { title: "ChatGPT Plus vs Google AI Pro in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of ChatGPT Plus (from ৳2,990/mo) and Google AI Pro (from ৳3,390/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/google-ai-pro-vs-chatgpt" },
  "/compare/chatgpt-vs-grammarly": { title: "ChatGPT Plus vs Grammarly Premium in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of ChatGPT Plus (from ৳2,990/mo) and Grammarly Premium (from ৳2,090/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/grammarly-vs-chatgpt" },
  "/compare/chatgpt-vs-grok": { title: "ChatGPT Plus vs Grok in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of ChatGPT Plus (from ৳2,990/mo) and Grok (from ৳1,495/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/grok-vs-chatgpt" },
  "/compare/chatgpt-vs-midjourney": { title: "ChatGPT Plus vs Midjourney in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of ChatGPT Plus (from ৳2,990/mo) and Midjourney (from ৳4,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/midjourney-vs-chatgpt" },
  "/compare/chatgpt-vs-notion": { title: "ChatGPT Plus vs Notion AI in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of ChatGPT Plus (from ৳2,990/mo) and Notion AI (Price on request). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/notion-vs-chatgpt" },
  "/compare/chatgpt-vs-perplexity": { title: "ChatGPT Plus vs Perplexity Pro in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of ChatGPT Plus (from ৳2,990/mo) and Perplexity Pro (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/chatgpt-vs-perplexity" },
  "/compare/chatgpt-vs-supergrok": { title: "ChatGPT Plus vs SuperGrok in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of ChatGPT Plus (from ৳2,990/mo) and SuperGrok (from ৳1,495/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/supergrok-vs-chatgpt" },
  "/compare/chatgpt-vs-vault": { title: "ChatGPT Plus vs AI Tools Vault in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of ChatGPT Plus (from ৳2,990/mo) and AI Tools Vault (৳1,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/vault-vs-chatgpt" },
  "/compare/claude-vs-chatgpt": { title: "Claude Pro vs ChatGPT Plus in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Claude Pro (from ৳2,990/mo) and ChatGPT Plus (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/claude-vs-chatgpt" },
  "/compare/claude-vs-gemini": { title: "Claude Pro vs Gemini Advanced in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Claude Pro (from ৳2,990/mo) and Gemini Advanced (from ৳3,390/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/claude-vs-gemini" },
  "/compare/claude-vs-perplexity": { title: "Claude Pro vs Perplexity Pro in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Claude Pro (from ৳2,990/mo) and Perplexity Pro (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/claude-vs-perplexity" },
  "/compare/copilot-vs-chatgpt": { title: "GitHub Copilot Pro vs ChatGPT Plus in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of GitHub Copilot Pro (from ৳1,495/mo) and ChatGPT Plus (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/copilot-vs-chatgpt" },
  "/compare/elevenlabs-vs-runway": { title: "ElevenLabs vs Runway ML in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of ElevenLabs (from ৳748/mo) and Runway ML (from ৳1,794/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/elevenlabs-vs-runway" },
  "/compare/gemini-vs-chatgpt": { title: "Gemini Advanced vs ChatGPT Plus in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Gemini Advanced (from ৳3,390/mo) and ChatGPT Plus (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/gemini-vs-chatgpt" },
  "/compare/gemini-vs-claude": { title: "Gemini Advanced vs Claude Pro in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Gemini Advanced (from ৳3,390/mo) and Claude Pro (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/claude-vs-gemini" },
  "/compare/google-ai-pro-vs-chatgpt": { title: "Google AI Pro vs ChatGPT Plus in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Google AI Pro (from ৳3,390/mo) and ChatGPT Plus (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/google-ai-pro-vs-chatgpt" },
  "/compare/grammarly-vs-chatgpt": { title: "Grammarly Premium vs ChatGPT Plus in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Grammarly Premium (from ৳2,090/mo) and ChatGPT Plus (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/grammarly-vs-chatgpt" },
  "/compare/grok-vs-chatgpt": { title: "Grok vs ChatGPT Plus in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Grok (from ৳1,495/mo) and ChatGPT Plus (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/grok-vs-chatgpt" },
  "/compare/kling-vs-runway": { title: "Kling AI vs Runway ML in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Kling AI (Price on request) and Runway ML (from ৳1,794/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/runway-vs-kling" },
  "/compare/leonardo-vs-midjourney": { title: "Leonardo AI vs Midjourney in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Leonardo AI (Price on request) and Midjourney (from ৳4,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/midjourney-vs-leonardo" },
  "/compare/microsoft365-vs-notion": { title: "Microsoft 365 Copilot vs Notion AI in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Microsoft 365 Copilot (Price on request) and Notion AI (Price on request). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/microsoft365-vs-notion" },
  "/compare/midjourney-vs-canva": { title: "Midjourney vs Canva Pro in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Midjourney (from ৳4,990/mo) and Canva Pro (from ৳2,190/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/canva-vs-midjourney" },
  "/compare/midjourney-vs-chatgpt": { title: "Midjourney vs ChatGPT Plus in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Midjourney (from ৳4,990/mo) and ChatGPT Plus (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/midjourney-vs-chatgpt" },
  "/compare/midjourney-vs-leonardo": { title: "Midjourney vs Leonardo AI in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Midjourney (from ৳4,990/mo) and Leonardo AI (Price on request). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/midjourney-vs-leonardo" },
  "/compare/notion-vs-chatgpt": { title: "Notion AI vs ChatGPT Plus in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Notion AI (Price on request) and ChatGPT Plus (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/notion-vs-chatgpt" },
  "/compare/notion-vs-microsoft365": { title: "Notion AI vs Microsoft 365 Copilot in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Notion AI (Price on request) and Microsoft 365 Copilot (Price on request). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/microsoft365-vs-notion" },
  "/compare/perplexity-vs-chatgpt": { title: "Perplexity Pro vs ChatGPT Plus in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Perplexity Pro (from ৳2,990/mo) and ChatGPT Plus (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/chatgpt-vs-perplexity" },
  "/compare/perplexity-vs-claude": { title: "Perplexity Pro vs Claude Pro in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Perplexity Pro (from ৳2,990/mo) and Claude Pro (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/claude-vs-perplexity" },
  "/compare/runway-vs-elevenlabs": { title: "Runway ML vs ElevenLabs in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Runway ML (from ৳1,794/mo) and ElevenLabs (from ৳748/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/elevenlabs-vs-runway" },
  "/compare/runway-vs-kling": { title: "Runway ML vs Kling AI in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of Runway ML (from ৳1,794/mo) and Kling AI (Price on request). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/runway-vs-kling" },
  "/compare/supergrok-vs-chatgpt": { title: "SuperGrok vs ChatGPT Plus in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of SuperGrok (from ৳1,495/mo) and ChatGPT Plus (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/supergrok-vs-chatgpt" },
  "/compare/vault-vs-chatgpt": { title: "AI Tools Vault vs ChatGPT Plus in Bangladesh — Price, Features, Verdict | AI Team Premium", description: "Side-by-side comparison of AI Tools Vault (৳1,990/mo) and ChatGPT Plus (from ৳2,990/mo). Specs, Bangla quality, best use cases and which to buy from AI Team Premium.", canonical: "https://www.aiteampremium.com/compare/vault-vs-chatgpt" },
};

// Only these go in the sitemap. The reverse-order URL of each pair renders the
// same comparison and canonicalises here, so advertising both would be asking
// crawlers to index the same page twice.
export const CANONICAL_COMPARE_PATHS = [
  "/compare/canva-vs-midjourney",
  "/compare/chatgpt-vs-perplexity",
  "/compare/claude-vs-chatgpt",
  "/compare/claude-vs-gemini",
  "/compare/claude-vs-perplexity",
  "/compare/copilot-vs-chatgpt",
  "/compare/elevenlabs-vs-runway",
  "/compare/gemini-vs-chatgpt",
  "/compare/google-ai-pro-vs-chatgpt",
  "/compare/grammarly-vs-chatgpt",
  "/compare/grok-vs-chatgpt",
  "/compare/microsoft365-vs-notion",
  "/compare/midjourney-vs-chatgpt",
  "/compare/midjourney-vs-leonardo",
  "/compare/notion-vs-chatgpt",
  "/compare/runway-vs-kling",
  "/compare/supergrok-vs-chatgpt",
  "/compare/vault-vs-chatgpt"
];
