// GENERATED FILE — do not edit by hand.
// Source: client/src/data/products-catalog.json
// Regenerate: npm run gen:routes
//
// One entry per product family served by /tools/:slug in App.tsx. Merged into
// ROUTE_META so each product page ships its own title, description and
// canonical from the server instead of sharing one generic record.

export const PRODUCT_ROUTE_META = {
  "/tools/adobe-firefly-bangladesh": { title: "Adobe Firefly Price in Bangladesh — from ৳190/mo | AI Team Premium", description: "Buy Adobe Firefly in Bangladesh. From ৳190/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/adobe-firefly-bangladesh" },
  "/tools/b2b-implementation-bangladesh": { title: "B2B Implementation Service Price in Bangladesh — from ৳25,000/mo | AI Team Premium", description: "Buy B2B Implementation Service in Bangladesh. From ৳25,000/month. Pay with bKash or Nagad — no international card needed. Custom delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/b2b-implementation-bangladesh" },
  "/tools/business-package-bangladesh": { title: "Business Package Price in Bangladesh — from ৳15,000/mo | AI Team Premium", description: "Buy Business Package in Bangladesh. From ৳15,000/month. Pay with bKash or Nagad — no international card needed. 2-12 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/business-package-bangladesh" },
  "/tools/canva-pro-bangladesh": { title: "Canva Pro Price in Bangladesh — from ৳510/mo | AI Team Premium", description: "Buy Canva Pro in Bangladesh. From ৳510/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/canva-pro-bangladesh" },
  "/tools/capcut-pro-bangladesh": { title: "CapCut Pro Price in Bangladesh — from ৳399/mo | AI Team Premium", description: "Buy CapCut Pro in Bangladesh. From ৳399/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/capcut-pro-bangladesh" },
  "/tools/chatgpt-business-bangladesh": { title: "ChatGPT Business Price in Bangladesh — from ৳699/mo | AI Team Premium", description: "Buy ChatGPT Business in Bangladesh. From ৳699/month. 3 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/chatgpt-business-bangladesh" },
  "/tools/chatgpt-go-bangladesh": { title: "ChatGPT Go Price in Bangladesh — from ৳1,196/mo | AI Team Premium", description: "Buy ChatGPT Go in Bangladesh. From ৳1,196/month. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/chatgpt-go-bangladesh" },
  "/tools/chatgpt-plus-bangladesh": { title: "ChatGPT Plus Price in Bangladesh — from ৳350/mo | AI Team Premium", description: "Buy ChatGPT Plus in Bangladesh. From ৳350/month. 3 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/chatgpt-plus-bangladesh" },
  "/tools/chatgpt-pro-bangladesh": { title: "ChatGPT Pro Price in Bangladesh — from ৳29,900/mo | AI Team Premium", description: "Buy ChatGPT Pro in Bangladesh. From ৳29,900/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-12 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/chatgpt-pro-bangladesh" },
  "/tools/claude-pro-bangladesh": { title: "Claude Price in Bangladesh — from ৳1,495/mo | AI Team Premium", description: "Buy Claude in Bangladesh. From ৳1,495/month. 5 plans. Pay with bKash or Nagad — no international card needed. 5-15 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/claude-pro-bangladesh" },
  "/tools/cursor-bangladesh": { title: "Cursor Price in Bangladesh — from ৳2,990/mo | AI Team Premium", description: "Buy Cursor in Bangladesh. From ৳2,990/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/cursor-bangladesh" },
  "/tools/descript-pro-bangladesh": { title: "Descript Pro Price in Bangladesh — from ৳470/mo | AI Team Premium", description: "Buy Descript Pro in Bangladesh. From ৳470/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/descript-pro-bangladesh" },
  "/tools/elevenlabs-bangladesh": { title: "ElevenLabs Price in Bangladesh — from ৳748/mo | AI Team Premium", description: "Buy ElevenLabs in Bangladesh. From ৳748/month. 3 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/elevenlabs-bangladesh" },
  "/tools/freelancer-bundle-bangladesh": { title: "Freelancer Bundle Price in Bangladesh — from ৳3,999/mo | AI Team Premium", description: "Buy Freelancer Bundle in Bangladesh. From ৳3,999/month. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/freelancer-bundle-bangladesh" },
  "/tools/freepik-premium-bangladesh": { title: "Freepik Premium Price in Bangladesh — from ৳450/mo | AI Team Premium", description: "Buy Freepik Premium in Bangladesh. From ৳450/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/freepik-premium-bangladesh" },
  "/tools/gamma-bangladesh": { title: "Gamma Plus Price in Bangladesh — from ৳399/mo | AI Team Premium", description: "Buy Gamma Plus in Bangladesh. From ৳399/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/gamma-bangladesh" },
  "/tools/gemini-advanced-bangladesh": { title: "Google AI Pro (Gemini Advanced) Price in Bangladesh — from ৳3,390/mo | AI Team Premium", description: "Buy Google AI Pro (Gemini Advanced) in Bangladesh. From ৳3,390/month. Pay with bKash or Nagad — no international card needed. 5-15 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/gemini-advanced-bangladesh" },
  "/tools/github-copilot-bangladesh": { title: "GitHub Copilot Price in Bangladesh — from ৳1,495/mo | AI Team Premium", description: "Buy GitHub Copilot in Bangladesh. From ৳1,495/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/github-copilot-bangladesh" },
  "/tools/grammarly-premium-bangladesh": { title: "Grammarly Premium Price in Bangladesh — from ৳470/mo | AI Team Premium", description: "Buy Grammarly Premium in Bangladesh. From ৳470/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/grammarly-premium-bangladesh" },
  "/tools/heygen-bangladesh": { title: "HeyGen Creator Price in Bangladesh — from ৳1,499/mo | AI Team Premium", description: "Buy HeyGen Creator in Bangladesh. From ৳1,499/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/heygen-bangladesh" },
  "/tools/ideogram-bangladesh": { title: "Ideogram Price in Bangladesh — from ৳2,990/mo | AI Team Premium", description: "Buy Ideogram in Bangladesh. From ৳2,990/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/ideogram-bangladesh" },
  "/tools/jasper-ai-bangladesh": { title: "Jasper AI Creator Price in Bangladesh — from ৳1,520/mo | AI Team Premium", description: "Buy Jasper AI Creator in Bangladesh. From ৳1,520/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/jasper-ai-bangladesh" },
  "/tools/kling-ai-bangladesh": { title: "Kling AI Price in Bangladesh — from ৳270/mo | AI Team Premium", description: "Buy Kling AI in Bangladesh. From ৳270/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/kling-ai-bangladesh" },
  "/tools/leonardo-ai-bangladesh": { title: "Leonardo AI Price in Bangladesh — from ৳599/mo | AI Team Premium", description: "Buy Leonardo AI in Bangladesh. From ৳599/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/leonardo-ai-bangladesh" },
  "/tools/manus-ai-bangladesh": { title: "Manus AI Price in Bangladesh — from ৳2,500/mo | AI Team Premium", description: "Buy Manus AI in Bangladesh. From ৳2,500/month. Pay with bKash or Nagad — no international card needed. 2-12 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/manus-ai-bangladesh" },
  "/tools/microsoft-copilot-pro-bangladesh": { title: "Microsoft Copilot Pro Price in Bangladesh — from ৳780/mo | AI Team Premium", description: "Buy Microsoft Copilot Pro in Bangladesh. From ৳780/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/microsoft-copilot-pro-bangladesh" },
  "/tools/midjourney-bangladesh": { title: "Midjourney Price in Bangladesh — from ৳1,199/mo | AI Team Premium", description: "Buy Midjourney in Bangladesh. From ৳1,199/month. 6 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/midjourney-bangladesh" },
  "/tools/murf-ai-bangladesh": { title: "Murf AI Price in Bangladesh — from ৳740/mo | AI Team Premium", description: "Buy Murf AI in Bangladesh. From ৳740/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/murf-ai-bangladesh" },
  "/tools/notion-business-bangladesh": { title: "Notion Business Price in Bangladesh — from ৳800/mo | AI Team Premium", description: "Buy Notion Business in Bangladesh. From ৳800/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/notion-business-bangladesh" },
  "/tools/opus-clip-bangladesh": { title: "Opus Clip Price in Bangladesh — from ৳590/mo | AI Team Premium", description: "Buy Opus Clip in Bangladesh. From ৳590/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/opus-clip-bangladesh" },
  "/tools/otter-ai-bangladesh": { title: "Otter.ai Pro Price in Bangladesh — from ৳799/mo | AI Team Premium", description: "Buy Otter.ai Pro in Bangladesh. From ৳799/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/otter-ai-bangladesh" },
  "/tools/perplexity-pro-bangladesh": { title: "Perplexity Price in Bangladesh — from ৳350/mo | AI Team Premium", description: "Buy Perplexity in Bangladesh. From ৳350/month. 3 plans. Pay with bKash or Nagad — no international card needed. 5-15 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/perplexity-pro-bangladesh" },
  "/tools/pika-labs-bangladesh": { title: "Pika Labs Price in Bangladesh — from ৳310/mo | AI Team Premium", description: "Buy Pika Labs in Bangladesh. From ৳310/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/pika-labs-bangladesh" },
  "/tools/quillbot-premium-bangladesh": { title: "QuillBot Premium Price in Bangladesh — from ৳390/mo | AI Team Premium", description: "Buy QuillBot Premium in Bangladesh. From ৳390/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/quillbot-premium-bangladesh" },
  "/tools/replit-bangladesh": { title: "Replit Core Price in Bangladesh — from ৳3,390/mo | AI Team Premium", description: "Buy Replit Core in Bangladesh. From ৳3,390/month. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/replit-bangladesh" },
  "/tools/runway-bangladesh": { title: "Runway Price in Bangladesh — from ৳1,794/mo | AI Team Premium", description: "Buy Runway in Bangladesh. From ৳1,794/month. 3 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/runway-bangladesh" },
  "/tools/student-package-bangladesh": { title: "Student Essentials Package Price in Bangladesh — from ৳449/mo | AI Team Premium", description: "Buy Student Essentials Package in Bangladesh. From ৳449/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/student-package-bangladesh" },
  "/tools/suno-ai-bangladesh": { title: "Suno AI Price in Bangladesh — from ৳1,495/mo | AI Team Premium", description: "Buy Suno AI in Bangladesh. From ৳1,495/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/suno-ai-bangladesh" },
  "/tools/supergrok-bangladesh": { title: "SuperGrok Price in Bangladesh — from ৳1,495/mo | AI Team Premium", description: "Buy SuperGrok in Bangladesh. From ৳1,495/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/supergrok-bangladesh" },
  "/tools/synthesia-bangladesh": { title: "Synthesia Price in Bangladesh — from ৳700/mo | AI Team Premium", description: "Buy Synthesia in Bangladesh. From ৳700/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/synthesia-bangladesh" },
  "/tools/udio-bangladesh": { title: "Udio Pro Price in Bangladesh — from ৳499/mo | AI Team Premium", description: "Buy Udio Pro in Bangladesh. From ৳499/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/udio-bangladesh" },
  "/tools/v0-dev-bangladesh": { title: "v0.dev Pro Price in Bangladesh — from ৳999/mo | AI Team Premium", description: "Buy v0.dev Pro in Bangladesh. From ৳999/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/v0-dev-bangladesh" },
  "/tools/windsurf-bangladesh": { title: "Windsurf Pro Price in Bangladesh — from ৳590/mo | AI Team Premium", description: "Buy Windsurf Pro in Bangladesh. From ৳590/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/windsurf-bangladesh" },
  "/tools/writesonic-bangladesh": { title: "Writesonic Individual Price in Bangladesh — from ৳799/mo | AI Team Premium", description: "Buy Writesonic Individual in Bangladesh. From ৳799/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/writesonic-bangladesh" },
};

export const PRODUCT_PATHS = Object.keys(PRODUCT_ROUTE_META);
