// GENERATED FILE — do not edit by hand.
// Source: client/src/data/products-catalog.json
// Regenerate: npm run gen:routes
//
// One entry per product family served by /tools/:slug in App.tsx. Merged into
// ROUTE_META so each product page ships its own title, description and
// canonical from the server instead of sharing one generic record.

export const PRODUCT_ROUTE_META = {
  "/tools/adobe-creative-cloud-bangladesh": { title: "Adobe Creative Cloud in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Adobe Creative Cloud in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/adobe-creative-cloud-bangladesh" },
  "/tools/adobe-firefly-bangladesh": { title: "Adobe Firefly Price in Bangladesh — from ৳190/mo | AI Team Premium", description: "Buy Adobe Firefly in Bangladesh. From ৳190/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/adobe-firefly-bangladesh" },
  "/tools/b2b-implementation-bangladesh": { title: "B2B Implementation Service Price in Bangladesh — from ৳25,000/mo | AI Team Premium", description: "Buy B2B Implementation Service in Bangladesh. From ৳25,000/month. Pay with bKash or Nagad — no international card needed. Custom delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/b2b-implementation-bangladesh" },
  "/tools/beautiful-ai-bangladesh": { title: "Beautiful.ai in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Beautiful.ai in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/beautiful-ai-bangladesh" },
  "/tools/bolt-new-bangladesh": { title: "Bolt.new in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Bolt.new in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/bolt-new-bangladesh" },
  "/tools/business-package-bangladesh": { title: "Business Package Price in Bangladesh — from ৳15,000/mo | AI Team Premium", description: "Buy Business Package in Bangladesh. From ৳15,000/month. Pay with bKash or Nagad — no international card needed. 2-12 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/business-package-bangladesh" },
  "/tools/canva-pro-bangladesh": { title: "Canva Pro Price in Bangladesh — from ৳510/mo | AI Team Premium", description: "Buy Canva Pro in Bangladesh. From ৳510/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/canva-pro-bangladesh" },
  "/tools/capcut-pro-bangladesh": { title: "CapCut Pro Price in Bangladesh — from ৳399/mo | AI Team Premium", description: "Buy CapCut Pro in Bangladesh. From ৳399/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/capcut-pro-bangladesh" },
  "/tools/captions-app-bangladesh": { title: "Captions in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Captions in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/captions-app-bangladesh" },
  "/tools/chatgpt-business-bangladesh": { title: "ChatGPT Business Price in Bangladesh — from ৳699/mo | AI Team Premium", description: "Buy ChatGPT Business in Bangladesh. From ৳699/month. 3 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/chatgpt-business-bangladesh" },
  "/tools/chatgpt-go-bangladesh": { title: "ChatGPT Go Price in Bangladesh — from ৳1,196/mo | AI Team Premium", description: "Buy ChatGPT Go in Bangladesh. From ৳1,196/month. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/chatgpt-go-bangladesh" },
  "/tools/chatgpt-plus-bangladesh": { title: "ChatGPT Plus Price in Bangladesh — from ৳350/mo | AI Team Premium", description: "Buy ChatGPT Plus in Bangladesh. From ৳350/month. 3 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/chatgpt-plus-bangladesh" },
  "/tools/chatgpt-pro-bangladesh": { title: "ChatGPT Pro Price in Bangladesh — from ৳29,900/mo | AI Team Premium", description: "Buy ChatGPT Pro in Bangladesh. From ৳29,900/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-12 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/chatgpt-pro-bangladesh" },
  "/tools/claude-pro-bangladesh": { title: "Claude Price in Bangladesh — from ৳1,495/mo | AI Team Premium", description: "Buy Claude in Bangladesh. From ৳1,495/month. 5 plans. Pay with bKash or Nagad — no international card needed. 5-15 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/claude-pro-bangladesh" },
  "/tools/cursor-bangladesh": { title: "Cursor Price in Bangladesh — from ৳2,990/mo | AI Team Premium", description: "Buy Cursor in Bangladesh. From ৳2,990/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/cursor-bangladesh" },
  "/tools/descript-pro-bangladesh": { title: "Descript Pro Price in Bangladesh — from ৳470/mo | AI Team Premium", description: "Buy Descript Pro in Bangladesh. From ৳470/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/descript-pro-bangladesh" },
  "/tools/elevenlabs-bangladesh": { title: "ElevenLabs Price in Bangladesh — from ৳748/mo | AI Team Premium", description: "Buy ElevenLabs in Bangladesh. From ৳748/month. 3 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/elevenlabs-bangladesh" },
  "/tools/fathom-bangladesh": { title: "Fathom in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Fathom in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/fathom-bangladesh" },
  "/tools/figma-bangladesh": { title: "Figma Professional in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Figma Professional in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/figma-bangladesh" },
  "/tools/filmora-bangladesh": { title: "Filmora in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Filmora in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/filmora-bangladesh" },
  "/tools/fireflies-ai-bangladesh": { title: "Fireflies.ai in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Fireflies.ai in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/fireflies-ai-bangladesh" },
  "/tools/freelancer-bundle-bangladesh": { title: "Freelancer Bundle Price in Bangladesh — from ৳3,999/mo | AI Team Premium", description: "Buy Freelancer Bundle in Bangladesh. From ৳3,999/month. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/freelancer-bundle-bangladesh" },
  "/tools/freepik-premium-bangladesh": { title: "Freepik Premium Price in Bangladesh — from ৳450/mo | AI Team Premium", description: "Buy Freepik Premium in Bangladesh. From ৳450/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/freepik-premium-bangladesh" },
  "/tools/gamma-bangladesh": { title: "Gamma Plus Price in Bangladesh — from ৳399/mo | AI Team Premium", description: "Buy Gamma Plus in Bangladesh. From ৳399/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/gamma-bangladesh" },
  "/tools/gemini-advanced-bangladesh": { title: "Google AI Pro (Gemini Advanced) Price in Bangladesh — from ৳3,390/mo | AI Team Premium", description: "Buy Google AI Pro (Gemini Advanced) in Bangladesh. From ৳3,390/month. Pay with bKash or Nagad — no international card needed. 5-15 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/gemini-advanced-bangladesh" },
  "/tools/github-copilot-bangladesh": { title: "GitHub Copilot Price in Bangladesh — from ৳1,495/mo | AI Team Premium", description: "Buy GitHub Copilot in Bangladesh. From ৳1,495/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/github-copilot-bangladesh" },
  "/tools/google-workspace-ai-bangladesh": { title: "Google Workspace with Gemini in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Google Workspace with Gemini in Bangladesh. Pay with bKash or Nagad — no international card needed. Up to 12 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/google-workspace-ai-bangladesh" },
  "/tools/grammarly-premium-bangladesh": { title: "Grammarly Premium Price in Bangladesh — from ৳470/mo | AI Team Premium", description: "Buy Grammarly Premium in Bangladesh. From ৳470/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/grammarly-premium-bangladesh" },
  "/tools/hailuo-ai-bangladesh": { title: "Hailuo AI (MiniMax) in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Hailuo AI (MiniMax) in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/hailuo-ai-bangladesh" },
  "/tools/heygen-bangladesh": { title: "HeyGen Creator Price in Bangladesh — from ৳1,499/mo | AI Team Premium", description: "Buy HeyGen Creator in Bangladesh. From ৳1,499/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/heygen-bangladesh" },
  "/tools/ideogram-bangladesh": { title: "Ideogram Price in Bangladesh — from ৳2,990/mo | AI Team Premium", description: "Buy Ideogram in Bangladesh. From ৳2,990/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/ideogram-bangladesh" },
  "/tools/jasper-ai-bangladesh": { title: "Jasper AI Creator Price in Bangladesh — from ৳1,520/mo | AI Team Premium", description: "Buy Jasper AI Creator in Bangladesh. From ৳1,520/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/jasper-ai-bangladesh" },
  "/tools/kling-ai-bangladesh": { title: "Kling AI Price in Bangladesh — from ৳270/mo | AI Team Premium", description: "Buy Kling AI in Bangladesh. From ৳270/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/kling-ai-bangladesh" },
  "/tools/krea-ai-bangladesh": { title: "Krea AI in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Krea AI in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/krea-ai-bangladesh" },
  "/tools/krisp-bangladesh": { title: "Krisp in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Krisp in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/krisp-bangladesh" },
  "/tools/leonardo-ai-bangladesh": { title: "Leonardo AI Price in Bangladesh — from ৳599/mo | AI Team Premium", description: "Buy Leonardo AI in Bangladesh. From ৳599/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/leonardo-ai-bangladesh" },
  "/tools/lovable-bangladesh": { title: "Lovable in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Lovable in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/lovable-bangladesh" },
  "/tools/luma-dream-machine-bangladesh": { title: "Luma Dream Machine in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Luma Dream Machine in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/luma-dream-machine-bangladesh" },
  "/tools/manus-ai-bangladesh": { title: "Manus AI Price in Bangladesh — from ৳2,500/mo | AI Team Premium", description: "Buy Manus AI in Bangladesh. From ৳2,500/month. Pay with bKash or Nagad — no international card needed. 2-12 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/manus-ai-bangladesh" },
  "/tools/microsoft-365-copilot-bangladesh": { title: "Microsoft 365 Copilot in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Microsoft 365 Copilot in Bangladesh. Pay with bKash or Nagad — no international card needed. Up to 12 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/microsoft-365-copilot-bangladesh" },
  "/tools/microsoft-copilot-pro-bangladesh": { title: "Microsoft Copilot Pro Price in Bangladesh — from ৳780/mo | AI Team Premium", description: "Buy Microsoft Copilot Pro in Bangladesh. From ৳780/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/microsoft-copilot-pro-bangladesh" },
  "/tools/midjourney-bangladesh": { title: "Midjourney Price in Bangladesh — from ৳1,199/mo | AI Team Premium", description: "Buy Midjourney in Bangladesh. From ৳1,199/month. 6 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/midjourney-bangladesh" },
  "/tools/murf-ai-bangladesh": { title: "Murf AI Price in Bangladesh — from ৳740/mo | AI Team Premium", description: "Buy Murf AI in Bangladesh. From ৳740/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/murf-ai-bangladesh" },
  "/tools/notion-business-bangladesh": { title: "Notion Business Price in Bangladesh — from ৳800/mo | AI Team Premium", description: "Buy Notion Business in Bangladesh. From ৳800/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/notion-business-bangladesh" },
  "/tools/opus-clip-bangladesh": { title: "Opus Clip Price in Bangladesh — from ৳590/mo | AI Team Premium", description: "Buy Opus Clip in Bangladesh. From ৳590/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/opus-clip-bangladesh" },
  "/tools/otter-ai-bangladesh": { title: "Otter.ai Pro Price in Bangladesh — from ৳799/mo | AI Team Premium", description: "Buy Otter.ai Pro in Bangladesh. From ৳799/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/otter-ai-bangladesh" },
  "/tools/perplexity-pro-bangladesh": { title: "Perplexity Price in Bangladesh — from ৳350/mo | AI Team Premium", description: "Buy Perplexity in Bangladesh. From ৳350/month. 3 plans. Pay with bKash or Nagad — no international card needed. 5-15 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/perplexity-pro-bangladesh" },
  "/tools/photoroom-bangladesh": { title: "Photoroom in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Photoroom in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/photoroom-bangladesh" },
  "/tools/pika-labs-bangladesh": { title: "Pika Labs Price in Bangladesh — from ৳310/mo | AI Team Premium", description: "Buy Pika Labs in Bangladesh. From ৳310/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/pika-labs-bangladesh" },
  "/tools/playht-bangladesh": { title: "PlayHT in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy PlayHT in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/playht-bangladesh" },
  "/tools/plus-ai-bangladesh": { title: "Plus AI in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Plus AI in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/plus-ai-bangladesh" },
  "/tools/poe-bangladesh": { title: "Poe in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Poe in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/poe-bangladesh" },
  "/tools/quillbot-premium-bangladesh": { title: "QuillBot Premium Price in Bangladesh — from ৳390/mo | AI Team Premium", description: "Buy QuillBot Premium in Bangladesh. From ৳390/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/quillbot-premium-bangladesh" },
  "/tools/recraft-bangladesh": { title: "Recraft in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Recraft in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/recraft-bangladesh" },
  "/tools/replit-bangladesh": { title: "Replit Core Price in Bangladesh — from ৳3,390/mo | AI Team Premium", description: "Buy Replit Core in Bangladesh. From ৳3,390/month. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/replit-bangladesh" },
  "/tools/runway-bangladesh": { title: "Runway Price in Bangladesh — from ৳1,794/mo | AI Team Premium", description: "Buy Runway in Bangladesh. From ৳1,794/month. 3 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/runway-bangladesh" },
  "/tools/speechify-bangladesh": { title: "Speechify Reader in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy Speechify Reader in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/speechify-bangladesh" },
  "/tools/student-package-bangladesh": { title: "Student Essentials Package Price in Bangladesh — from ৳449/mo | AI Team Premium", description: "Buy Student Essentials Package in Bangladesh. From ৳449/month. 2 plans. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/student-package-bangladesh" },
  "/tools/suno-ai-bangladesh": { title: "Suno AI Price in Bangladesh — from ৳1,495/mo | AI Team Premium", description: "Buy Suno AI in Bangladesh. From ৳1,495/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/suno-ai-bangladesh" },
  "/tools/supergrok-bangladesh": { title: "SuperGrok Price in Bangladesh — from ৳1,495/mo | AI Team Premium", description: "Buy SuperGrok in Bangladesh. From ৳1,495/month. 2 plans. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/supergrok-bangladesh" },
  "/tools/synthesia-bangladesh": { title: "Synthesia Price in Bangladesh — from ৳700/mo | AI Team Premium", description: "Buy Synthesia in Bangladesh. From ৳700/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/synthesia-bangladesh" },
  "/tools/udio-bangladesh": { title: "Udio Pro Price in Bangladesh — from ৳499/mo | AI Team Premium", description: "Buy Udio Pro in Bangladesh. From ৳499/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/udio-bangladesh" },
  "/tools/v0-dev-bangladesh": { title: "v0.dev Pro Price in Bangladesh — from ৳999/mo | AI Team Premium", description: "Buy v0.dev Pro in Bangladesh. From ৳999/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/v0-dev-bangladesh" },
  "/tools/veed-bangladesh": { title: "VEED in Bangladesh — Pricing & Plans | AI Team Premium", description: "Buy VEED in Bangladesh. Pay with bKash or Nagad — no international card needed. 2-4 hours delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/veed-bangladesh" },
  "/tools/windsurf-bangladesh": { title: "Windsurf Pro Price in Bangladesh — from ৳590/mo | AI Team Premium", description: "Buy Windsurf Pro in Bangladesh. From ৳590/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/windsurf-bangladesh" },
  "/tools/writesonic-bangladesh": { title: "Writesonic Individual Price in Bangladesh — from ৳799/mo | AI Team Premium", description: "Buy Writesonic Individual in Bangladesh. From ৳799/month. Pay with bKash or Nagad — no international card needed. 5-30 min delivery, 30-day replacement guarantee, Bangla WhatsApp support.", canonical: "https://www.aiteampremium.com/tools/writesonic-bangladesh" },
};

export const PRODUCT_PATHS = Object.keys(PRODUCT_ROUTE_META);

// Counts used in site copy. Generated so a growing catalog can never leave a
// stale "80 tools" claim behind in a title or meta description.
//   TOOL_COUNT    distinct products (one per page) — what a visitor calls a tool
//   PRODUCT_COUNT purchasable tiers across those products — what /all-products lists
export const TOOL_COUNT = 66;
export const PRODUCT_COUNT = 102;
