// GENERATED FILE — do not edit by hand.
// Source: client/src/data/products-catalog.json
// Regenerate: npm run gen:routes
//
// One entry per product family served by /tools/:slug in App.tsx. Merged into
// ROUTE_META so each product page ships its own title, description and
// canonical from the server instead of sharing one generic record.

export const PRODUCT_ROUTE_META = {
  "/tools/adobe-creative-cloud-bangladesh": { title: "Adobe Creative Cloud in Bangladesh — Pricing & Plans | AI Team Premium", description: "Adobe Creative Cloud in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/adobe-creative-cloud-bangladesh" },
  "/tools/adobe-firefly-bangladesh": { title: "Adobe Firefly in Bangladesh — Pricing & Plans | AI Team Premium", description: "Adobe Firefly in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/adobe-firefly-bangladesh" },
  "/tools/ahrefs-bangladesh": { title: "Ahrefs Price in Bangladesh — from ৳4,992/mo | AI Team Premium", description: "Ahrefs in Bangladesh. From ৳4,992/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/ahrefs-bangladesh" },
  "/tools/airtable-bangladesh": { title: "Airtable Price in Bangladesh — from ৳3,440/mo | AI Team Premium", description: "Airtable in Bangladesh. From ৳3,440/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/airtable-bangladesh" },
  "/tools/b2b-implementation-bangladesh": { title: "B2B Implementation Service Price in Bangladesh — from ৳25,000/mo | AI Team Premium", description: "B2B Implementation Service in Bangladesh. From ৳25,000/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/b2b-implementation-bangladesh" },
  "/tools/beautiful-ai-bangladesh": { title: "Beautiful.ai Price in Bangladesh — from ৳2,064/mo | AI Team Premium", description: "Beautiful.ai in Bangladesh. From ৳2,064/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/beautiful-ai-bangladesh" },
  "/tools/bolt-new-bangladesh": { title: "Bolt.new Price in Bangladesh — from ৳4,304/mo | AI Team Premium", description: "Bolt.new in Bangladesh. From ৳4,304/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/bolt-new-bangladesh" },
  "/tools/business-package-bangladesh": { title: "Business Package Price in Bangladesh — from ৳15,000/mo | AI Team Premium", description: "Business Package in Bangladesh. From ৳15,000/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/business-package-bangladesh" },
  "/tools/canva-pro-bangladesh": { title: "Canva Pro Price in Bangladesh — from ৳2,190/mo | AI Team Premium", description: "Canva Pro in Bangladesh. From ৳2,190/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/canva-pro-bangladesh" },
  "/tools/capcut-pro-bangladesh": { title: "CapCut Pro in Bangladesh — Pricing & Plans | AI Team Premium", description: "CapCut Pro in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/capcut-pro-bangladesh" },
  "/tools/captions-app-bangladesh": { title: "Captions Price in Bangladesh — from ৳1,728/mo | AI Team Premium", description: "Captions in Bangladesh. From ৳1,728/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/captions-app-bangladesh" },
  "/tools/chatgpt-business-bangladesh": { title: "ChatGPT Business Price in Bangladesh — from ৳4,990/mo | AI Team Premium", description: "ChatGPT Business in Bangladesh. From ৳4,990/month. 3 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/chatgpt-business-bangladesh" },
  "/tools/chatgpt-go-bangladesh": { title: "ChatGPT Go Price in Bangladesh — from ৳1,196/mo | AI Team Premium", description: "ChatGPT Go in Bangladesh. From ৳1,196/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/chatgpt-go-bangladesh" },
  "/tools/chatgpt-plus-bangladesh": { title: "ChatGPT Plus Price in Bangladesh — from ৳2,990/mo | AI Team Premium", description: "ChatGPT Plus in Bangladesh. From ৳2,990/month. 3 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/chatgpt-plus-bangladesh" },
  "/tools/chatgpt-pro-bangladesh": { title: "ChatGPT Pro Price in Bangladesh — from ৳29,900/mo | AI Team Premium", description: "ChatGPT Pro in Bangladesh. From ৳29,900/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/chatgpt-pro-bangladesh" },
  "/tools/claude-pro-bangladesh": { title: "Claude Price in Bangladesh — from ৳2,990/mo | AI Team Premium", description: "Claude in Bangladesh. From ৳2,990/month. 5 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/claude-pro-bangladesh" },
  "/tools/clickup-bangladesh": { title: "ClickUp Price in Bangladesh — from ৳1,216/mo | AI Team Premium", description: "ClickUp in Bangladesh. From ৳1,216/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/clickup-bangladesh" },
  "/tools/coursera-plus-bangladesh": { title: "Coursera Plus Price in Bangladesh — from ৳2,304/mo | AI Team Premium", description: "Coursera Plus in Bangladesh. From ৳2,304/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/coursera-plus-bangladesh" },
  "/tools/cursor-bangladesh": { title: "Cursor Price in Bangladesh — from ৳2,990/mo | AI Team Premium", description: "Cursor in Bangladesh. From ৳2,990/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/cursor-bangladesh" },
  "/tools/descript-pro-bangladesh": { title: "Descript Pro Price in Bangladesh — from ৳2,090/mo | AI Team Premium", description: "Descript Pro in Bangladesh. From ৳2,090/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/descript-pro-bangladesh" },
  "/tools/elevenlabs-bangladesh": { title: "ElevenLabs Price in Bangladesh — from ৳748/mo | AI Team Premium", description: "ElevenLabs in Bangladesh. From ৳748/month. 3 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/elevenlabs-bangladesh" },
  "/tools/fathom-bangladesh": { title: "Fathom Price in Bangladesh — from ৳2,752/mo | AI Team Premium", description: "Fathom in Bangladesh. From ৳2,752/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/fathom-bangladesh" },
  "/tools/figma-bangladesh": { title: "Figma Professional Price in Bangladesh — from ৳2,064/mo | AI Team Premium", description: "Figma Professional in Bangladesh. From ৳2,064/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/figma-bangladesh" },
  "/tools/filmora-bangladesh": { title: "Filmora Price in Bangladesh — from ৳1,008/mo | AI Team Premium", description: "Filmora in Bangladesh. From ৳1,008/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/filmora-bangladesh" },
  "/tools/fireflies-ai-bangladesh": { title: "Fireflies.ai Price in Bangladesh — from ৳1,728/mo | AI Team Premium", description: "Fireflies.ai in Bangladesh. From ৳1,728/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/fireflies-ai-bangladesh" },
  "/tools/framer-bangladesh": { title: "Framer Price in Bangladesh — from ৳1,728/mo | AI Team Premium", description: "Framer in Bangladesh. From ৳1,728/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/framer-bangladesh" },
  "/tools/freelancer-bundle-bangladesh": { title: "Freelancer Bundle Price in Bangladesh — from ৳3,999/mo | AI Team Premium", description: "Freelancer Bundle in Bangladesh. From ৳3,999/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/freelancer-bundle-bangladesh" },
  "/tools/freepik-premium-bangladesh": { title: "Freepik Premium in Bangladesh — Pricing & Plans | AI Team Premium", description: "Freepik Premium in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/freepik-premium-bangladesh" },
  "/tools/gamma-bangladesh": { title: "Gamma Plus in Bangladesh — Pricing & Plans | AI Team Premium", description: "Gamma Plus in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/gamma-bangladesh" },
  "/tools/gemini-advanced-bangladesh": { title: "Google AI Pro (Gemini Advanced) Price in Bangladesh — from ৳3,390/mo | AI Team Premium", description: "Google AI Pro (Gemini Advanced) in Bangladesh. From ৳3,390/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/gemini-advanced-bangladesh" },
  "/tools/github-copilot-bangladesh": { title: "GitHub Copilot Price in Bangladesh — from ৳1,495/mo | AI Team Premium", description: "GitHub Copilot in Bangladesh. From ৳1,495/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/github-copilot-bangladesh" },
  "/tools/google-workspace-ai-bangladesh": { title: "Google Workspace with Gemini Price in Bangladesh — from ৳2,416/mo | AI Team Premium", description: "Google Workspace with Gemini in Bangladesh. From ৳2,416/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/google-workspace-ai-bangladesh" },
  "/tools/grammarly-premium-bangladesh": { title: "Grammarly Premium Price in Bangladesh — from ৳2,090/mo | AI Team Premium", description: "Grammarly Premium in Bangladesh. From ৳2,090/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/grammarly-premium-bangladesh" },
  "/tools/hailuo-ai-bangladesh": { title: "Hailuo AI (MiniMax) Price in Bangladesh — from ৳2,592/mo | AI Team Premium", description: "Hailuo AI (MiniMax) in Bangladesh. From ৳2,592/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/hailuo-ai-bangladesh" },
  "/tools/heygen-bangladesh": { title: "HeyGen Creator in Bangladesh — Pricing & Plans | AI Team Premium", description: "HeyGen Creator in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/heygen-bangladesh" },
  "/tools/ideogram-bangladesh": { title: "Ideogram Price in Bangladesh — from ৳2,990/mo | AI Team Premium", description: "Ideogram in Bangladesh. From ৳2,990/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/ideogram-bangladesh" },
  "/tools/jasper-ai-bangladesh": { title: "Jasper AI Creator Price in Bangladesh — from ৳5,830/mo | AI Team Premium", description: "Jasper AI Creator in Bangladesh. From ৳5,830/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/jasper-ai-bangladesh" },
  "/tools/kling-ai-bangladesh": { title: "Kling AI in Bangladesh — Pricing & Plans | AI Team Premium", description: "Kling AI in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/kling-ai-bangladesh" },
  "/tools/krea-ai-bangladesh": { title: "Krea AI Price in Bangladesh — from ৳1,552/mo | AI Team Premium", description: "Krea AI in Bangladesh. From ৳1,552/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/krea-ai-bangladesh" },
  "/tools/krisp-bangladesh": { title: "Krisp Price in Bangladesh — from ৳1,376/mo | AI Team Premium", description: "Krisp in Bangladesh. From ৳1,376/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/krisp-bangladesh" },
  "/tools/leonardo-ai-bangladesh": { title: "Leonardo AI in Bangladesh — Pricing & Plans | AI Team Premium", description: "Leonardo AI in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/leonardo-ai-bangladesh" },
  "/tools/loom-bangladesh": { title: "Loom — Business Price in Bangladesh — from ৳3,104/mo | AI Team Premium", description: "Loom — Business in Bangladesh. From ৳3,104/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/loom-bangladesh" },
  "/tools/lovable-bangladesh": { title: "Lovable Price in Bangladesh — from ৳4,304/mo | AI Team Premium", description: "Lovable in Bangladesh. From ৳4,304/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/lovable-bangladesh" },
  "/tools/luma-dream-machine-bangladesh": { title: "Luma Dream Machine Price in Bangladesh — from ৳1,728/mo | AI Team Premium", description: "Luma Dream Machine in Bangladesh. From ৳1,728/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/luma-dream-machine-bangladesh" },
  "/tools/make-bangladesh": { title: "Make Price in Bangladesh — from ৳1,552/mo | AI Team Premium", description: "Make in Bangladesh. From ৳1,552/month. 3 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/make-bangladesh" },
  "/tools/manus-ai-bangladesh": { title: "Manus AI Price in Bangladesh — from ৳2,500/mo | AI Team Premium", description: "Manus AI in Bangladesh. From ৳2,500/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/manus-ai-bangladesh" },
  "/tools/microsoft-365-copilot-bangladesh": { title: "Microsoft 365 Copilot in Bangladesh — Pricing & Plans | AI Team Premium", description: "Microsoft 365 Copilot in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/microsoft-365-copilot-bangladesh" },
  "/tools/microsoft-copilot-pro-bangladesh": { title: "Microsoft Copilot Pro Price in Bangladesh — from ৳2,990/mo | AI Team Premium", description: "Microsoft Copilot Pro in Bangladesh. From ৳2,990/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/microsoft-copilot-pro-bangladesh" },
  "/tools/midjourney-bangladesh": { title: "Midjourney Price in Bangladesh — from ৳4,990/mo | AI Team Premium", description: "Midjourney in Bangladesh. From ৳4,990/month. 6 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/midjourney-bangladesh" },
  "/tools/miro-bangladesh": { title: "Miro Price in Bangladesh — from ৳1,376/mo | AI Team Premium", description: "Miro in Bangladesh. From ৳1,376/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/miro-bangladesh" },
  "/tools/mistral-le-chat-bangladesh": { title: "Mistral Le Chat Price in Bangladesh — from ৳2,592/mo | AI Team Premium", description: "Mistral Le Chat in Bangladesh. From ৳2,592/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/mistral-le-chat-bangladesh" },
  "/tools/murf-ai-bangladesh": { title: "Murf AI Price in Bangladesh — from ৳2,840/mo | AI Team Premium", description: "Murf AI in Bangladesh. From ৳2,840/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/murf-ai-bangladesh" },
  "/tools/notion-business-bangladesh": { title: "Notion Business in Bangladesh — Pricing & Plans | AI Team Premium", description: "Notion Business in Bangladesh. 2 plans. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/notion-business-bangladesh" },
  "/tools/opus-clip-bangladesh": { title: "Opus Clip Price in Bangladesh — from ৳2,590/mo | AI Team Premium", description: "Opus Clip in Bangladesh. From ৳2,590/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/opus-clip-bangladesh" },
  "/tools/otter-ai-bangladesh": { title: "Otter.ai Pro in Bangladesh — Pricing & Plans | AI Team Premium", description: "Otter.ai Pro in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/otter-ai-bangladesh" },
  "/tools/perplexity-pro-bangladesh": { title: "Perplexity Price in Bangladesh — from ৳2,990/mo | AI Team Premium", description: "Perplexity in Bangladesh. From ৳2,990/month. 3 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/perplexity-pro-bangladesh" },
  "/tools/photoroom-bangladesh": { title: "Photoroom Price in Bangladesh — from ৳1,296/mo | AI Team Premium", description: "Photoroom in Bangladesh. From ৳1,296/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/photoroom-bangladesh" },
  "/tools/pika-labs-bangladesh": { title: "Pika Labs Price in Bangladesh — from ৳1,200/mo | AI Team Premium", description: "Pika Labs in Bangladesh. From ৳1,200/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/pika-labs-bangladesh" },
  "/tools/playht-bangladesh": { title: "PlayHT Price in Bangladesh — from ৳5,376/mo | AI Team Premium", description: "PlayHT in Bangladesh. From ৳5,376/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/playht-bangladesh" },
  "/tools/plus-ai-bangladesh": { title: "Plus AI Price in Bangladesh — from ৳1,728/mo | AI Team Premium", description: "Plus AI in Bangladesh. From ৳1,728/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/plus-ai-bangladesh" },
  "/tools/poe-bangladesh": { title: "Poe Price in Bangladesh — from ৳3,440/mo | AI Team Premium", description: "Poe in Bangladesh. From ৳3,440/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/poe-bangladesh" },
  "/tools/quillbot-premium-bangladesh": { title: "QuillBot Premium Price in Bangladesh — from ৳1,490/mo | AI Team Premium", description: "QuillBot Premium in Bangladesh. From ৳1,490/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/quillbot-premium-bangladesh" },
  "/tools/recraft-bangladesh": { title: "Recraft Price in Bangladesh — from ৳1,728/mo | AI Team Premium", description: "Recraft in Bangladesh. From ৳1,728/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/recraft-bangladesh" },
  "/tools/replit-bangladesh": { title: "Replit Core Price in Bangladesh — from ৳3,390/mo | AI Team Premium", description: "Replit Core in Bangladesh. From ৳3,390/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/replit-bangladesh" },
  "/tools/runway-bangladesh": { title: "Runway Price in Bangladesh — from ৳1,794/mo | AI Team Premium", description: "Runway in Bangladesh. From ৳1,794/month. 3 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/runway-bangladesh" },
  "/tools/semrush-bangladesh": { title: "Semrush Price in Bangladesh — from ৳20,176/mo | AI Team Premium", description: "Semrush in Bangladesh. From ৳20,176/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/semrush-bangladesh" },
  "/tools/speechify-bangladesh": { title: "Speechify Reader Price in Bangladesh — from ৳2,000/mo | AI Team Premium", description: "Speechify Reader in Bangladesh. From ৳2,000/month. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/speechify-bangladesh" },
  "/tools/student-package-bangladesh": { title: "Student Essentials Package Price in Bangladesh — from ৳449/mo | AI Team Premium", description: "Student Essentials Package in Bangladesh. From ৳449/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/student-package-bangladesh" },
  "/tools/suno-ai-bangladesh": { title: "Suno AI Price in Bangladesh — from ৳1,495/mo | AI Team Premium", description: "Suno AI in Bangladesh. From ৳1,495/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/suno-ai-bangladesh" },
  "/tools/supergrok-bangladesh": { title: "SuperGrok Price in Bangladesh — from ৳1,495/mo | AI Team Premium", description: "SuperGrok in Bangladesh. From ৳1,495/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/supergrok-bangladesh" },
  "/tools/surfer-seo-bangladesh": { title: "Surfer SEO Price in Bangladesh — from ৳8,432/mo | AI Team Premium", description: "Surfer SEO in Bangladesh. From ৳8,432/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/surfer-seo-bangladesh" },
  "/tools/synthesia-bangladesh": { title: "Synthesia in Bangladesh — Pricing & Plans | AI Team Premium", description: "Synthesia in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/synthesia-bangladesh" },
  "/tools/udio-bangladesh": { title: "Udio Pro in Bangladesh — Pricing & Plans | AI Team Premium", description: "Udio Pro in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/udio-bangladesh" },
  "/tools/v0-dev-bangladesh": { title: "v0.dev Pro in Bangladesh — Pricing & Plans | AI Team Premium", description: "v0.dev Pro in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/v0-dev-bangladesh" },
  "/tools/veed-bangladesh": { title: "VEED Price in Bangladesh — from ৳1,728/mo | AI Team Premium", description: "VEED in Bangladesh. From ৳1,728/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/veed-bangladesh" },
  "/tools/windsurf-bangladesh": { title: "Windsurf Pro in Bangladesh — Pricing & Plans | AI Team Premium", description: "Windsurf Pro in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/windsurf-bangladesh" },
  "/tools/writesonic-bangladesh": { title: "Writesonic Individual in Bangladesh — Pricing & Plans | AI Team Premium", description: "Writesonic Individual in Bangladesh. Pricing, access model and availability are confirmed after plan verification — ask on WhatsApp before payment.", canonical: "https://www.aiteampremium.com/tools/writesonic-bangladesh" },
  "/tools/zapier-bangladesh": { title: "Zapier Price in Bangladesh — from ৳3,440/mo | AI Team Premium", description: "Zapier in Bangladesh. From ৳3,440/month. 2 plans. Current access model, availability, fulfillment timing and support terms are confirmed before purchase. Ask on WhatsApp for the current order instructions.", canonical: "https://www.aiteampremium.com/tools/zapier-bangladesh" },
};

export const PRODUCT_PATHS = Object.keys(PRODUCT_ROUTE_META);

// Counts used in site copy. Generated so a growing catalog can never leave a
// stale "80 tools" claim behind in a title or meta description.
//   TOOL_COUNT    distinct products (one per page) — what a visitor calls a tool
//   PRODUCT_COUNT purchasable tiers across those products — what /all-products lists
export const TOOL_COUNT = 78;
export const PRODUCT_COUNT = 129;

// Prices quoted in hand-written site copy, derived from the catalog so a repriced
// tier cannot leave a stale number in a title or meta description.
export const PRICE_ANCHORS = {
  "catalogMin": 449,
  "chatgptPlusPersonal": 2990
};
